server:
  port: ${SERVER_PORT:8432}

spring:
  application:
    name: @project.name@
  config:
    import:
      - classpath:/logging.yml
  devtools:
    restart:
      enabled: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
